export declare const MALLFORMED_RESPONSE_ERROR = 'Mallformed Response from server'
export declare const TABLES_LENGTH_DIFFERS = 'Tables have different lengths!'
export declare const FIELD_NOT_EXIST = 'Field not exists in Table!'
export declare const VALUE_OUT_OF_LIMITS = 'Value out of limits!'
export declare const EMPTY_VALUES = 'Empty Values provided'
