export const MALLFORMED_RESPONSE_ERROR = 'Mallformed Response from server'
export const TABLES_LENGTH_DIFFERS = 'Tables have different lengths!'
export const FIELD_NOT_EXIST = 'Field not exists in Table!'
export const VALUE_OUT_OF_LIMITS = 'Value out of limits!'
export const EMPTY_VALUES = 'Empty Values provided'
